### ISSUE TITLE
no devices

### ISSUE THREAD

**Issue by lasry1** [sahilchaddha/homebridge-yeelight-platform#1]
Hi,

I have it 'running' but it doesn't discover / add the lights

[2018-11-9 23:06:56] [Yeelight-Platform] Initializing Yeelight-Platform platform...
[2018-11-9 23:06:56] Loading 2 accessories...

**Comment by sahilchaddha** [comment]
Hey @lasry1 , 
Can u enable `debug` in your homebridge config and show us full logs ? 
It will help us identify the issue.

Usually turning power off lights and turning them on fixes discovery.
If lights have been turned on for a long period of time, they dont respond to discovery message. Try restarting lights & then restarting homebridge.
