### ISSUE TITLE
Add support for yeelink.light.strip1

### ISSUE THREAD

**Issue by andrewostroumov** [sahilchaddha/homebridge-yeelight-platform#11]
Is there a chance to add yeelight led strip support to your nice package?
https://www.yeelight.com/en_US/product/pitaya

**Comment by iwonder-1618** [comment]
Hey @andrewostroumov ,
If your yeelight follows Official Yeelight API. This plugin should work with it. Make sure you enable `LAN Control` for your device using Yeelight App.

**Comment by andrewostroumov** [comment]
Thank you. After enabling it works
