### ISSUE TITLE
Support for Mijia desk lamp?

### ISSUE THREAD

**Issue by brandonzh** [sahilchaddha/homebridge-yeelight-platform#17]
Hi,
I have a Mijia desk lamp connected to the yeelight app. But it seems homebridge cannot found the device (The LAN control is on). Can you double check if this device is supported? 
https://www.yeelight.com/en_US/product/mijia-lamp.

Thank you!

**Comment by sahilchaddha** [comment]
I dont have this device to test currently. Till the time Desk Lamp support official Yeelight API it should work. 
If you face any issue, feel free to comment and re-open the ticket
