### ISSUE TITLE
Home bridge launch problem.

### ISSUE THREAD

**Issue by ShibaeO** [sahilchaddha/homebridge-yeelight-platform#7]
Hello,

Recenly i installed homebridge with yeelight and it was work good,
but when i install your plugin this is what i get:

thanks for help :)
![capture](https://user-images.githubusercontent.com/42607264/49825438-b8a2fd80-fd84-11e8-9f01-90bafad0c4e2.PNG)

**Comment by sahilchaddha** [comment]
Hey @ShibaeO , Please make sure you uninstall `homebridge-yeelight` properly first. I can see from the logs that `homebridge-yeelight` is also installed and used. Both plugins need socket port `1982`.

**Comment by ShibaeO** [comment]
Hi,

Thanks for reply after uninstall homebridge-yeelight and reinstall homebridge-yeelight-platform, i put config .json and when i start homebridge this is what i get :
![capture](https://user-images.githubusercontent.com/42607264/49849751-51fcfe80-fddb-11e8-8540-02eeee1491f5.PNG)

Im sorry for all this problem ;)

**Comment by sahilchaddha** [comment]
Hey @ShibaeO , Now this looks like that you already have a running homebridge instance.
Port 51826 is used by homebridge. Try restarting your system, it should remove any zombie instances running. Or try setting a different port number in config.json
