### ISSUE TITLE
Option to add "shouldTurnOff" per scene.

### ISSUE THREAD

**Issue by Aekung** [sahilchaddha/homebridge-yeelight-platform#9]
Yesterday I successfully uninstalled homebridge-yeelight-wifi and installed your plugin instead. Yeelight-Wifi is a great plugin but lack of the scene function as seen in your plugin. So thank you very much for such an awesome plugin.

BTW, it would be great if you could make "shouldTurnOff" available for each scene since there will be time where we want to turn only specific scene off automatically when it's triggered.

Thank you and really hope you would consider this.

**Comment by sahilchaddha** [comment]
@Aekung ,

Updated the plugin to `1.2.1`

Sample config
```
            "shouldTurnOff": true,
            "pollingInterval": 20000,
            "scenes": [
                {
                    "name": "Disco Time",
                    "scene": "disco",
                    "shouldTurnOff": false
                },
               {
                    "name": "Night Mode",
                    "scene": "night_mode"
                },
```
E.g.
shouldTurnOff for disco => false
shouldTurnOff for night_mode => true

Scene `shouldTurnOff` will override Global `shouldTurnOff`

**Comment by Aekung** [comment]
@sahilchaddha Wow! This is neat and fast! Thank you very much for your respond and quick update.

I will update and try it now.

Thank you very much.

**Comment by sahilchaddha** [comment]
@Aekung , I am glad it worked out for you.
